name: CI
on:
  push:
    branches: [master]
jobs:
  build-linux:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          # sudo apt update
      - name: Build
        run: |
          cd tests
          make
          make run
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          # brew update
      - name: Build
        run: |
          cd tests
          make
          make run
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          version: 12.2.0
          platform: x64
          hardlinks: 1
      - name: Install dependencies
        run: |
          # ./install_deps.bat
      - name: Build
        run: |
          cd tests
          ./build.bat
      - name: Run
        run: |
          #  ./test.exe
