name: CI
on:
  push:
    branches: [master]
jobs:
  build-linux:
    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-22.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          # sudo apt update
      - name: Build and run
        run: |
          cd tests
          make OPT=0
          make run
          make clean
          make OPT=3
          make run
  build-macos:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          # brew update
      - name: Build and run
        run: |
          cd tests
          make
          make run
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v1
      - name: Clean up PATH
        uses: egor-tensin/cleanup-path@v3
      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          version: 12.2.0
          platform: x64
          hardlinks: 1
      - name: Install dependencies
        run: |
          # ./install_deps.bat
      - name: Build
        run: |
          cd tests
          ./build.bat
      - name: Run
        run: |
          ./test.exe
